swiss_cities = [
    ("Geneve", "Lausanne"),
    ("Lausanne", "Friburg"),
    ("Lausanne", "Yverdon-les-Bains"),
    ("Lausanne", "Montreux"),
    ("Yverdon-les-Bains", "Neuchatel"),
    ("Neuchatel", "Basel"),
    ("Neuchatel", "Bern"),
    ("Friburg", "Bern"),
    ("Bern", "Thun"),
    ("Thun", "Interlaken"),
    ("Interlaken", "Luzern"),
    ("Interlaken", "Disentis"),
    ("Montreux", "Mantigny"),
    ("Mantigny", "Sion"),
    ("Sion", "Brig"),
    ("Brig", "Disentis"),
    ("Disentis", "St.Moritz"),
    ("Disentis", "Chur"),
    ("Luzern", "Chur"),
    ("Chur", "St.Gallen"),
    ("Luzern", "Zurich"),
    ("Zurich", "St.Gallen"),
    ("Basel", "Luzern"),
    ("Luzern", "Zurich"),
]

swiss_cities_with_weight = [
    ("Geneve", "Lausanne", {"weight": 3}),
    ("Lausanne", "Friburg", {"weight": 4}),
    ("Lausanne", "Yverdon-les-Bains", {"weight": 3}),
    ("Lausanne", "Montreux", {"weight": 5}),
    ("Yverdon-les-Bains", "Neuchatel", {"weight": 2}),
    ("Neuchatel", "Basel", {"weight": 2}),
    ("Neuchatel", "Bern", {"weight": 4}),
    ("Friburg", "Bern", {"weight": 3}),
    ("Bern", "Thun", {"weight": 1}),
    ("Thun", "Interlaken", {"weight": 2}),
    ("Interlaken", "Luzern", {"weight": 5}),
    ("Interlaken", "Disentis", {"weight": 2}),
    ("Montreux", "Mantigny", {"weight": 3}),
    ("Mantigny", "Sion", {"weight": 2}),
    ("Sion", "Brig", {"weight": 4}),
    ("Brig", "Disentis", {"weight": 3}),
    ("Disentis", "St.Moritz", {"weight": 2}),
    ("Disentis", "Chur", {"weight": 5}),
    ("Luzern", "Chur", {"weight": 4}),
    ("Chur", "St.Gallen", {"weight": 4}),
    ("Luzern", "Zurich", {"weight": 3}),
    ("Zurich", "St.Gallen", {"weight": 5}),
    ("Basel", "Luzern", {"weight": 2}),
    ("Luzern", "Zurich", {"weight": 3}),
]