swiss_cities = [
    ("Geneve", "Lausanne"),
    ("Lausanne", "Friburg"),
    ("Lausanne", "Yverdon-les-Bains"),
    ("Lausanne", "Montreux"),
    ("Yverdon-les-Bains", "Neuchatel"),
    ("Neuchatel", "Basel"),
    ("Neuchatel", "Bern"),
    ("Friburg", "Bern"),
    ("Bern", "Thun"),
    ("Thun", "Interlaken"),
    ("Interlaken", "Luzern"),
    ("Interlaken", "Disentis"),
    ("Montreux", "Mantigny"),
    ("Mantigny", "Sion"),
    ("Sion", "Brig"),
    ("Brig", "Disentis"),
    ("Disentis", "St.Moritz"),
    ("Disentis", "Chur"),
    ("Luzern", "Chur"),
    ("Chur", "St.Gallen"),
    ("Luzern", "Zurich"),
    ("Zurich", "St.Gallen"),
    ("Basel", "Luzern"),
    ("Luzern", "Zurich"),
]